name: Test Browsers
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # weekly
    - cron: '0 0 * * 0'

jobs:
  edge_dev:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        repository: microsoft/playwright
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: microsoft/playwright-github-action@v1
    - name: Install Microsoft Edge
      run: |
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-dev.list'
        sudo apt-get update
        sudo apt-get -y install microsoft-edge-dev
    - name: Install dependencies
      run: npm ci
    - name: Build Playwright
      run: npm run build
    - name: Run tests
      run: xvfb-run npm run ctest
      env:
        CRPATH: /usr/bin/microsoft-edge
  chrome_stable:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        repository: microsoft/playwright
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: microsoft/playwright-github-action@v1
    - name: Install Google Chrome
      run: |
        curl -# -o chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i chrome.deb
        rm chrome.deb
    - name: Install dependencies
      run: npm ci
    - name: Build Playwright
      run: npm run build
    - name: Run tests
      run: xvfb-run npm run ctest
      env:
        CRPATH: /usr/bin/google-chrome-stable